name: "Test the website during PR to master"
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: "Checkout action"
        uses: actions/checkout@v1.0.0
      - name: "Setup julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: "1.2.0"
      - name: "Setup hugo"
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.62.2'
      - name: "Install the packages"
        run: julia --project -e 'import Pkg; Pkg.activate("."); Pkg.update();Pkg.instantiate(); Pkg.build()'
      - name: "Weave the lessons"
        run: |
          julia --project -e 'using Weave; weave(joinpath("content", "lessons", "planning_ahead.Jmd"), doctype="hugo")'
          julia --project -e 'using Weave; weave(joinpath("content", "lessons", "control_flow.Jmd"), doctype="hugo")'
          julia --project -e 'using Weave; weave(joinpath("content", "lessons", "writing_functions.Jmd"), doctype="hugo")'
          julia --project -e 'using Weave; weave(joinpath("content", "lessons", "avoiding_mistakes.Jmd"), doctype="hugo")'
      - name: "Weave the capstones"
        run: |
          julia --project -e 'using Weave; weave(joinpath("content", "capstones", "abc.Jmd"), doctype="hugo")'
          julia --project -e 'using Weave; weave(joinpath("content", "capstones", "genetic_algorithm.Jmd"), doctype="hugo")'
          julia --project -e 'using Weave; weave(joinpath("content", "capstones", "runge_kutta.Jmd"), doctype="hugo")'
      - name: "Weave the primers"
        run: |
          julia --project -e 'using Weave; weave(joinpath("content", "primers", "advanced_control_flow.Jmd"), doctype="hugo")'
          julia --project -e 'using Weave; weave(joinpath("content", "primers", "indexing.Jmd"), doctype="hugo")'
          julia --project -e 'using Weave; weave(joinpath("content", "primers", "map_filter_reduce.Jmd"), doctype="hugo")'
          julia --project -e 'using Weave; weave(joinpath("content", "primers", "optimization.Jmd"), doctype="hugo")'
          julia --project -e 'using Weave; weave(joinpath("content", "primers", "parallelcomputing.Jmd"), doctype="hugo")'
      - name: "Weave the machine learning modules"
        run: |
          julia --project -e 'using Weave; weave(joinpath("content", "machinelearning", "neural_network_flux.Jmd"), doctype="hugo")'
          julia --project -e 'using Weave; weave(joinpath("content", "machinelearning", "naive_bayesian_classifier.Jmd"), doctype="hugo")'
      - name: "Build the website"
        run: hugo
