name: "Build the website for deployment"
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        julia: [1.5.2]
        document: ["lessons/01_planning_ahead/", "lessons/02_control_flow/"]
    steps:
      - name: "Checkout action"
        uses: actions/checkout@v1.0.0
      - name: "Setup julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia }}
      - name: "Build the core packages"
        uses: julia-actions/julia-buildpkg@master
      - name: "Setup hugo"
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.62.2'
      - name: "Build ${{ matrix.document }}"
        run: |
          julia -e """
            import Pkg
            using Weave
            source_file = joinpath("content", ${{ matrix.document }}, "_index.Jmd")
            target_file = joinpath("dist", replace(source_file, "index.Jmd" => "index.md"))
            cd(joinpath("content", ${{ matrix.document }}))
            Pkg.activate(".")
            post_name = splitpath(current_post_folder)[end]
            weave(
              source_file,
              out_path = target_file,
              doctype = "github",
              # doctype = "hugo",
              # fig_path = joinpath(post_name, "figures")
            )
            cd("..", "..")
          """"
        - name: Upload result for ${{ matrix.document }}
          uses: actions/upload-artifact@v2
          with:
            name: built
            path: dist